# Курсовая работа студента факультета искусственного интеллекта онлайн-университета [Geek University](https://geekbrains.ru/geek_university)

## В рамках курса "Python для Data Science"  

Полная версия

**Автор**: Кабанов Сергей  
**Преподаватель**: Ширкин Сергей

**Материалы к проекту (файлы)**:  
train.csv  
test.csv

**Задание**:  
Используя данные из train.csv, построить модель для предсказания цен на недвижимость (квартиры). С помощью полученной модели предсказать цены для квартир из файла test.csv.

**Целевая переменная**:  
Price

**Основная метрика**:  
R2 - коэффициент детерминации (sklearn.metrics.r2_score)

**Вспомогательная метрика**:  
MSE - средняя квадратичная ошибка (sklearn.metrics.mean_squared_error)

In [1]:
RANDOM_STATE = 42

### Data load (загрузка данных)

В данном разделе выполним загрузку данных в объекты типа DataFrame и проверим корректность данных.

In [2]:
import pandas as pd

TRAIN_DATA_FILE = 'train.csv'
TEST_DATA_FILE = 'test.csv'

In [3]:
# загрузка данных
data_train = pd.read_csv(TRAIN_DATA_FILE)
data_test = pd.read_csv(TEST_DATA_FILE)

Необходимо проверить загруженные данные.

In [4]:
# проверяем количество объектов и признаков
data_train.shape, data_test.shape

((10000, 20), (5000, 19))

In [5]:
# смотрим как выглядят данные, правильно ли прочитался файл, нет ли проблем с разделителями/кодировкой
data_train.head()

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
0  14038          35    2.0  47.981561   29.442751            6.0      7   
1  15053          41    3.0  65.683640   40.049543            8.0      7   
2   4765          53    2.0  44.947953   29.197612            0.0      8   
3   5809          58    2.0  53.352981   52.731512            9.0      8   
4  10783          99    1.0  39.649192   23.776169            7.0     11   

   HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  \
0         9.0       1969   0.089040         B         B        33      7976   
1         9.0       1978   0.000070         B         B        46     10309   
2        12.0       1968   0.049637         B         B        34      7759   
3        17.0       1977   0.437885         B         B        23      5735   
4        12.0       1976   0.012339         B         B        35      5776   

   Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2          Price  
0         5           NaN            0       11       B  184966.930730  
1         1         240.0            1       16       B  300009.450063  
2         0         229.0            1        3       B  220925.908524  
3         3        1084.0            0        5       B  175616.227217  
4         1        2078.0            2        4       B  150226.531644

In [6]:
# аналогично для test
data_test.head()

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
0    725          58    2.0  49.882643   33.432782            6.0      6   
1  15856          74    2.0  69.263183         NaN            1.0      6   
2   5480         190    1.0  13.597819   15.948246           12.0      2   
3  15664          47    2.0  73.046609   51.940842            9.0     22   
4  14275          27    1.0  47.527111   43.387569            1.0     17   

   HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  \
0        14.0       1972   0.310199         B         B        11      2748   
1         1.0       1977   0.075779         B         B         6      1437   
2         5.0       1909   0.000000         B         B        30      7538   
3        22.0       2007   0.101872         B         B        23      4583   
4        17.0       2017   0.072158         B         B         2       629   

   Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  
0         1           NaN            0        0       B  
1         3           NaN            0        2       B  
2        87        4702.0            5        5       B  
3         3           NaN            3        3       B  
4         1           NaN            0        0       A

Имеем 10000 квартир в наборе train, и 5000 квартир для которых нужно сделать предсказание. Данные загружены корректно.

### Data analysis (анализ данных)

В данном разделе выполним первичный анализ данных на предмет аномалий, неадекватных/пропущенных значений. Попробуем понять что собой представляют признаки. Так же исправим не системные ошибки.

In [7]:
# Посмотрим на названия признаков, наличие пропущенных и нечисловых значений.
data_train.info();

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
Id               10000 non-null int64
DistrictId       10000 non-null int64
Rooms            10000 non-null float64
Square           10000 non-null float64
LifeSquare       7887 non-null float64
KitchenSquare    10000 non-null float64
Floor            10000 non-null int64
HouseFloor       10000 non-null float64
HouseYear        10000 non-null int64
Ecology_1        10000 non-null float64
Ecology_2        10000 non-null object
Ecology_3        10000 non-null object
Social_1         10000 non-null int64
Social_2         10000 non-null int64
Social_3         10000 non-null int64
Healthcare_1     5202 non-null float64
Helthcare_2      10000 non-null int64
Shops_1          10000 non-null int64
Shops_2          10000 non-null object
Price            10000 non-null float64
dtypes: float64(8), int64(9), object(3)
memory usage: 1.5+ MB


Ряд признаков имеет вполне понятный смысл (от Id до HouseYear, а так же Price). Остальные признаки вероятно говорят о характеристике района, чем самой квартиры. Экологическая ситуация (загрязнение воздуха, город/загород?), социальные показатели (школы, сады, криминал?), показатели здравоохранения (характеристики больниц? аптеки?), а так же информация по магазинам (удаленность, количество, размеры?)

Всего у двух признаков имеются пропущенные значения. Предварительно данные для жилой площади можно попробовать заполнить статистическим значениями. А вот отсутсвие данных по признаку Healthcare_1 может быть вызвано тем, что для этих квартир данная оценка например равна 0, что является нормальным значением.

Три признака являются строками. Их нужно будет приводить к числам.

In [8]:
# Посмотрим на статистики по признакам. Транспонируем вывод для удобства чтения.
data_train.describe().T

count           mean            std           min  \
Id             10000.0    8383.407700    4859.019020      0.000000   
DistrictId     10000.0      50.400800      43.587592      0.000000   
Rooms          10000.0       1.890500       0.839512      0.000000   
Square         10000.0      56.315775      21.058732      1.136859   
LifeSquare      7887.0      37.199645      86.241209      0.370619   
KitchenSquare  10000.0       6.273300      28.560917      0.000000   
Floor          10000.0       8.526700       5.241148      1.000000   
HouseFloor     10000.0      12.609400       6.775974      0.000000   
HouseYear      10000.0    3990.166300  200500.261427   1910.000000   
Ecology_1      10000.0       0.118858       0.119025      0.000000   
Social_1       10000.0      24.687000      17.532614      0.000000   
Social_2       10000.0    5352.157400    4006.799803    168.000000   
Social_3       10000.0       8.039200      23.831875      0.000000   
Healthcare_1    5202.0    1142.904460    1021.517264      0.000000   
Helthcare_2    10000.0       1.319500       1.493601      0.000000   
Shops_1        10000.0       4.231300       4.806341      0.000000   
Price          10000.0  214138.857399   92872.293865  59174.778028   

                         25%            50%            75%           max  
Id               4169.500000    8394.500000   12592.500000  1.679800e+04  
DistrictId         20.000000      36.000000      75.000000  2.090000e+02  
Rooms               1.000000       2.000000       2.000000  1.900000e+01  
Square             41.774881      52.513310      65.900625  6.410652e+02  
LifeSquare         22.769832      32.781260      45.128803  7.480592e+03  
KitchenSquare       1.000000       6.000000       9.000000  2.014000e+03  
Floor               4.000000       7.000000      12.000000  4.200000e+01  
HouseFloor          9.000000      13.000000      17.000000  1.170000e+02  
HouseYear        1974.000000    1977.000000    2001.000000  2.005201e+07  
Ecology_1           0.017647       0.075424       0.195781  5.218671e-01  
Social_1            6.000000      25.000000      36.000000  7.400000e+01  
Social_2         1564.000000    5285.000000    7227.000000  1.908300e+04  
Social_3            0.000000       2.000000       5.000000  1.410000e+02  
Healthcare_1      350.000000     900.000000    1548.000000  4.849000e+03  
Helthcare_2         0.000000       1.000000       2.000000  6.000000e+00  
Shops_1             1.000000       3.000000       6.000000  2.300000e+01  
Price          153872.633942  192269.644879  249135.462171  6.332335e+05

Пройдемся по признакам c понятным смыслом. Запишем вопросы и заметки.

Rooms:  
квартиры без комнат, возможно студии?  
квартира с 19 комнатами  

Square:  
квартиры с очень маленькой площадью, квартиры с площадью менее 15 метров выглядят подозрительно  
квартиры с очень большой площадью (разница между 3 квартилем и максимальным значением слишком большая)  

LifeSquare:  
аналогично Square  
пропущенные значения  

KitchenSquare:  
есть квартиры без кухни?  
максимальное значение похоже на год, вероятно опечатка при заполнении данных  

Floor:  
42 этаж выглядит подозрительно, учитывая, что третий квартиль равен 12  

HouseFloor:  
дома с нулем этажей?  
максимум равен 117, вероятно это опечатка и значение должно быть равно 17  

HouseYear:  
максимум выглядит как опечатка, 2.005201e+07 это скорее всего либо 2005, либо 201* какой-то год  


#### HouseYear

In [9]:
# посмотрим на слишком большие знаечения поля HouseYear
data_train.loc[data_train['HouseYear'] > 2020]

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
1497  10814         109    1.0  37.265070   20.239714            9.0      9   
4189  11607         147    2.0  44.791836   28.360393            5.0      4   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
1497        12.0   20052011   0.136330         B         B        30   
4189         9.0       4968   0.319809         B         B        25   

      Social_2  Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  \
1497      6141        10         262.0            3        6       B   
4189      4756        16        2857.0            5        8       B   

              Price  
1497  254084.534396  
4189  243028.603096

In [10]:
# заменим 20052011 на 2005
data_train.loc[data_train['HouseYear'] == 20052011, 'HouseYear'] = 2005

# заменим 4968 на 1968
data_train.loc[data_train['HouseYear'] == 4968, 'HouseYear'] = 1968

#### HouseFloor

In [13]:
# посмотрим на большие значения поля HouseFloor
data_train.loc[data_train['HouseFloor'] > 50]

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
6131  10806           5    1.0  51.944587   48.709601            1.0      6   
8599   9300          74    2.0  71.747869   74.579809            9.0      5   
8854     78          30    2.0  65.773749   66.811789            1.0      8   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
6131        99.0       1977   0.150818         B         B        16   
8599        99.0       1977   0.075779         B         B         6   
8854       117.0       1977   0.000078         B         B        22   

      Social_2  Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  \
6131      3433         4        2643.0            4        5       B   
8599      1437         3           NaN            0        2       B   
8854      6398       141        1046.0            3       23       B   

              Price  
6131  296127.115515  
8599  243329.912579  
8854  207248.370520

In [14]:
# заменим 99 на 9
data_train.loc[data_train['HouseFloor'] == 99, 'HouseFloor'] = 9

# заменим 117 на 17
data_train.loc[data_train['HouseFloor'] == 117, 'HouseFloor'] = 17

In [16]:
# посмотрим на квартиры с нулем этажей
data_train.loc[data_train['HouseFloor'] == 0]

Id  DistrictId  Rooms      Square  LifeSquare  KitchenSquare  Floor  \
7     11993          74    2.0   80.312926         NaN            0.0     14   
23     6641          54    3.0  118.907612         NaN            0.0      2   
26     4378          27    3.0  106.958871    0.641822            0.0     17   
39     9371          23    2.0   60.503248         NaN            0.0     16   
44    10521          38    3.0  104.211396  106.340403            0.0     20   
65    11398          62    1.0   41.194188         NaN            0.0      6   
70    10362          27    2.0   79.227049         NaN            0.0      9   
195    4645          54    2.0   76.312851         NaN            0.0     14   
223    4622          27    2.0   62.153994   36.094352            0.0      5   
252    8139          27    2.0   58.553809         NaN            0.0      7   
444    6224          59    3.0  106.349245         NaN            0.0      7   
501   15923          27    1.0   26.553188         NaN            0.0     25   
556    8610          35    1.0   47.410775         NaN            0.0      4   
562    6916          27    1.0   43.011789   22.158763            0.0     17   
594    8093          45    2.0   62.933064         NaN            0.0     18   
667    9684          88    3.0   86.431890         NaN            0.0     11   
700   11548          27    2.0   41.610104         NaN            0.0      7   
730   12947          53    2.0   56.023342         NaN            0.0     14   
805   15931           1    2.0   77.330279         NaN            0.0      1   
823    1498          45    3.0   83.515103         NaN            0.0     11   
839    9925          62    1.0   42.805164         NaN            0.0     14   
847   11828          27    1.0   52.539365         NaN            0.0     11   
861   15131          27    2.0   60.299356         NaN            0.0      5   
889    3429          27    1.0   47.020680         NaN            0.0      8   
896    6036          95    1.0   46.248238         NaN            0.0      5   
900    8940          34    1.0   26.811587         NaN            0.0     18   
924   11875           6    2.0   65.070052         NaN            0.0     11   
929    1827          27    1.0   38.037790         NaN            0.0      7   
932    9383          24    2.0   88.407297         NaN            0.0      2   
942    4711           6    1.0   41.224118         NaN            0.0      8   
...     ...         ...    ...         ...         ...            ...    ...   
8888    184          23    1.0   56.786709         NaN            0.0      3   
8893  11090           1    1.0   41.197082   40.808976            0.0     12   
8930  11532          23    2.0   55.550541   56.802256            0.0      7   
8954   6581          62    2.0   65.131558         NaN            0.0     11   
8979  13670          22    1.0   87.485627         NaN            0.0     16   
8996  15661          45    3.0   81.094922         NaN            0.0     15   
9014   4405          74    2.0   71.207458         NaN            0.0      5   
9030   8329          62    3.0   86.443771         NaN            0.0      3   
9057  14564          34    4.0   97.524848   97.046136            1.0     20   
9087   7767           1    2.0   90.856881         NaN            0.0     11   
9092  13884          45    2.0   62.460577         NaN            0.0      5   
9122   9150           6    1.0   43.067590         NaN            0.0     18   
9199   8755          62    2.0   79.329878         NaN            0.0     17   
9219   1737          23    1.0   59.963701         NaN            0.0      9   
9268  13665          62    2.0   57.717659         NaN            0.0     10   
9312  12761          27    1.0   37.667044   15.894112            8.0      9   
9359    842          74    1.0   52.133425         NaN            0.0     18   
9395  16371          62    3.0   88.961872         NaN            0.0     10   
9432    3

Квартир с признаком HouseFloor = 0 много (269 шт.), это явно системная аномалия. Так же похоже, что у большинства таких квартир признак HouseYear = 1977. Проверим это наблюдение.

In [17]:
# количество квартир с нулевым значением HouseFloor по году постройки дома
data_train.loc[data_train['HouseFloor'] == 0]['HouseYear'].value_counts()

1977    253
2016      6
2018      4
2015      4
2017      1
2014      1
Name: HouseYear, dtype: int64

Наблюдение подтвердилось. Нули по признаку HouseFloor нужно будет заполнять по статистическим данным.

#### Floor

In [18]:
# посмотрим на большие значения поля Floor
data_train.loc[data_train['Floor'] > 40]

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
2781  1674          76    2.0  74.344672   41.044132            5.0     42   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
2781        48.0       2016        0.0         B         B         7   

      Social_2  Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  \
2781      1660        39        1786.0            1        5       B   

              Price  
2781  411691.504766

Вполне нормальное значение. Оставляем без изменений.

#### KitchenSquare

In [19]:
# посмотрим на большие значения поля KitchenSquare
data_train.loc[data_train['KitchenSquare'] > 20]

Id  DistrictId  Rooms      Square  LifeSquare  KitchenSquare  Floor  \
227   16395           2    3.0   79.722243   44.731219           72.0     12   
551    1315           6    1.0   48.128114   45.023531           48.0     21   
622   12924          30    3.0   92.473796   53.649526           22.0      3   
1064  14656          62    1.0   47.100719   46.447960         2014.0      4   
1077   9690          27    1.0   40.081042   37.834964           37.0     18   
1369   2371          27    2.0   68.841073   64.234956           66.0      4   
1455  12507          54    2.0   79.810535   79.578961           78.0     10   
1804  11459          79    1.0   98.727990   49.781722           22.0     18   
1860   4265         161    2.0   53.216778   32.644859           53.0      7   
1867   3267          58    3.0  138.980817  138.004600           43.0      2   
1982   5548          86    5.0  275.645284  233.949309           26.0     12   
2656  14556         183    4.0  151.150660   98.187482           23.0      6   
2916  12390          72    3.0   97.490674   99.323558           96.0     22   
2969   7441          62    3.0  114.734473  112.589083          112.0      3   
3368   6674          54    1.0  168.086347  125.486563           30.0     18   
3379  16781          27    1.0   36.138409   36.710539           36.0     19   
3431   7111          27    2.0  139.070296   89.787666           42.0      5   
4079   6508          23    2.0   67.146049   33.959154           63.0      5   
4110    299          27    2.0   66.787523   64.616662           60.0     14   
4142  15466          88    1.0   42.357487   44.779714           41.0     10   
4588    448          48    1.0   41.186904    1.626502           41.0      2   
4651  12552          58    3.0  116.405693  113.109653          112.0      3   
5087  15947         129    4.0  185.906396   84.830074           31.0      5   
5149  13703          42    1.0   38.071692   19.723548           73.0      9   
5162  11739          27    2.0   61.070298   59.845092           58.0      8   
5480  15781          10    1.0   35.813564   19.953992           35.0      6   
5494    300          31    2.0  106.427686   34.230415           32.0      4   
5653   8500          31    1.0   80.606246   25.299592           29.0      6   
5816   2271          27    1.0   43.292516   42.835643           40.0     12   
5849  11624          46    1.0   42.983283   24.224435           37.0     15   
5888  16593          52    2.0   64.859242         NaN           62.0     15   
5904    673          27    1.0   54.418214   51.498581           51.0     10   
6036  12666          34    2.0   60.603363    2.400832           58.0     14   
6240   4966          96    3.0   78.445675   47.146757           75.0      9   
6988   8685          62    5.0  124.933289   81.122369           30.0      5   
7088   6569          27    1.0   38.220258   18.716856           84.0      4   
7201   3233         129    4.0  186.692602   87.487080           32.0      3   
7249   3431          62    2.0   60.715426   40.720961           25.0      5   
7480  10546          62    1.0   46.013187   43.417043           43.0      4   
8182  16511          52    3.0  135.731888   71.583248           21.0     26   
8232   7162          34    2.0   56.738764   57.510395           54.0     26   
8390  13559          79    1.0   96.838013   49.140960           22.0     19   
8584  14679          81    1.0   32.276663   19.278394         1970.0      6   
8921  12074          94    3.0  108.957285   51.063721           27.0      2   
9111   6708          48    1.0   42.069359   22.487739           39.0      1   
9889  12918          23    2.0   51.440463   53.134243           51.0      3   
9895   2737          27    3.0  123.430072  125.806981          123.0      5   
9910  16568          27    4.0  200.334539  201.627361           25.0      1   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
227         16.0

Наблюдаем 48 не вполне адекватных значений. Где-то указан год, где-то площад кухни равна общей площади или жилой. Но есть и вполне нормальные значения (с учетом общей площади). Нужно будет считать отношение площади кухни к общей площади и править неадекватные значения. Сейчас оставляем без изменений.

Так же видим проблему с полями Floor и HouseFloor. Есть квартиры у которых Floor > HouseFloor.

Так же видим что у некоторых квартир не адекватное соотношение жилой площади к общей.

In [19]:
# посмотрим на маленькие значения поля KitchenSquare
data_train.loc[data_train['KitchenSquare'] < 1]

Id  DistrictId  Rooms      Square  LifeSquare  KitchenSquare  Floor  \
2      4765          53    2.0   44.947953   29.197612            0.0      8   
7     11993          74    2.0   80.312926         NaN            0.0     14   
23     6641          54    3.0  118.907612         NaN            0.0      2   
26     4378          27    3.0  106.958871    0.641822            0.0     17   
39     9371          23    2.0   60.503248         NaN            0.0     16   
42     9833           1    2.0   56.494318   54.723569            0.0      9   
44    10521          38    3.0  104.211396  106.340403            0.0     20   
52     2301           1    2.0   61.400054   65.224603            0.0     17   
65    11398          62    1.0   41.194188         NaN            0.0      6   
70    10362          27    2.0   79.227049         NaN            0.0      9   
71     2136          74    2.0   84.687732   81.905552            0.0     12   
72    14675          74    1.0   52.457589   52.423345            0.0     18   
161    4263          27    1.0   54.255191   51.135219            0.0      5   
167    7023           1    2.0   71.005575         NaN            0.0     11   
195    4645          54    2.0   76.312851         NaN            0.0     14   
223    4622          27    2.0   62.153994   36.094352            0.0      5   
231    2540           6    3.0   82.353023         NaN            0.0     13   
234   12633          27    3.0   81.867166   81.884548            0.0     12   
244   13137          23    1.0   43.790432         NaN            0.0     10   
246     790          23    1.0   41.074417         NaN            0.0      9   
252    8139          27    2.0   58.553809         NaN            0.0      7   
296     513          27    2.0   57.134181         NaN            0.0     16   
300    2395           1    2.0   64.699994   61.287766            0.0      4   
320   11173           6    2.0   62.648779         NaN            0.0      6   
333   11210          27    2.0   68.453814   66.918934            0.0     15   
339   11563           8    1.0   50.390862   41.642898            0.0     32   
341   13457           6    1.0   40.326128         NaN            0.0     16   
397    6781          58    1.0   53.161505         NaN            0.0      9   
400    2453          52    2.0   68.111212   64.181422            0.0      4   
444    6224          59    3.0  106.349245         NaN            0.0      7   
...     ...         ...    ...         ...         ...            ...    ...   
9534  15563          27    2.0   78.553375         NaN            0.0      7   
9535   4880          27    2.0   66.740267         NaN            0.0      8   
9562   2819          52    2.0   68.935850         NaN            0.0     16   
9573    805          27    3.0   80.701454         NaN            0.0     12   
9576   7389          23    1.0   52.028804    4.295819            0.0      8   
9578  11382          27    2.0   54.861381         NaN            0.0      2   
9593   2553          62    2.0   56.560809         NaN            0.0      9   
9604   7979           6    1.0   47.671275         NaN            0.0     20   
9606  12136           1    1.0   51.953707         NaN            0.0      2   
9616  12557           6    2.0   66.501773         NaN            0.0     14   
9626   3742           1    1.0   53.258610   56.655126            0.0      6   
9628  14936          27    3.0  103.587261         NaN            0.0      8   
9660  11320          27    1.0   41.299844         NaN            0.0      7   
9695  12400          23    3.0   80.789885         NaN            0.0      2   
9696  14403           6    1.0   39.772905         NaN            0.0     13   
9707  12302          30    1.0   46.072913   48.307844            0.0      4   
9730   8644          58    3.0   80.957312         NaN            0.0      6   
9740   3241           6    1.0   42.706178         NaN            0.0      7   
9769   93

У 697 квартир площадь кухни равна 0. Возможно это квартиры студии или данных по площади кузхни просто не было. Как вариант можно все неадекватные значения признака KitchenSquare занулить.

#### Floor > HouseFloor

In [20]:
# посмотрим на квартиры у которых этаж больше чем этажность дома, исключая дома с 0 этажей
data_train.loc[(data_train['Floor'] > data_train['HouseFloor']) & (data_train['HouseFloor'] > 0)]

Id  DistrictId  Rooms      Square  LifeSquare  KitchenSquare  Floor  \
14    10953          27    1.0   53.769097   52.408027            1.0      5   
16     2119          27    2.0   49.360648   31.993964            5.0      6   
21    11935          27    2.0   64.711835         NaN            1.0     15   
35     6486         200    3.0   85.280389   58.447967            9.0      6   
51    10103          94    1.0   35.280894   23.354176            6.0     11   
67     8443          57    2.0   45.964890   29.141212            5.0      7   
68     1063          77    1.0   42.678844   23.918634            8.0     14   
72    14675          74    1.0   52.457589   52.423345            0.0     18   
76    14020          34    1.0   47.909327   42.782385            1.0      2   
86     9613         148    3.0  127.481583         NaN            1.0     16   
87    16674          94    2.0   47.145626   30.738284            5.0     11   
95     4280          34    2.0   61.334968    4.091945            1.0     26   
104    2930           9    2.0   62.347154         NaN            1.0      6   
115   12377          27    2.0   60.445855         NaN            1.0     13   
119     367          45    1.0   42.367289   40.012529            1.0     16   
122    5267          49    1.0   43.444266   20.702409            8.0     18   
123    8753          25    3.0   85.952306   89.803753            1.0      4   
129    6072           6    1.0   65.102017   64.622603            1.0     10   
131   10726          27    3.0   89.692964   87.623814            1.0     13   
141    3839          31    3.0   78.471987   52.706824            8.0      6   
145   14787          34    2.0   60.366626   57.709149           10.0     20   
152   14141          23    2.0   57.699619         NaN           10.0      2   
153    9870          62    1.0   51.831473   53.491301            1.0      5   
155   14109          62    1.0   47.577280   43.123508            1.0      6   
156   14258          44    2.0   44.511407   29.847462            5.0      6   
157   15848          23    3.0   70.214575   49.364085            9.0      3   
160    3522           6    1.0   66.419841    3.987101            1.0      2   
161    4263          27    1.0   54.255191   51.135219            0.0      5   
167    7023           1    2.0   71.005575         NaN            0.0     11   
170    4747           7    3.0   81.467909   76.646182           10.0     19   
...     ...         ...    ...         ...         ...            ...    ...   
9821   3469          27    3.0  103.654338         NaN            1.0      5   
9822  12992          75    2.0   47.917740   29.839365            5.0      7   
9828  13630          24    3.0  127.141143    4.811405            1.0      3   
9837   5482         157    2.0   48.185943   33.156377            7.0      9   
9847    759          29    1.0   36.298652   20.959605            6.0      7   
9852  16641         111    4.0  117.201937   69.898092           14.0      4   
9853  12913           8    2.0   48.406418   30.717760            5.0     13   
9869  16299         107    2.0   57.284603   34.599765            7.0      6   
9870    309          27    1.0   37.551366         NaN            1.0     11   
9871   6121          48    1.0   41.783808   41.944790            1.0     17   
9872  14136          12    1.0   43.711302   20.130061            8.0     18   
9917   1901          94    1.0   45.822669         NaN            1.0      7   
9924   3327         145    1.0   41.093702   20.643619            8.0     18   
9931  13355          27    2.0   64.261856         NaN            1.0     10   
9938  15868           9    2.0   64.412326   61.337938            1.0     13   
9942   9369           1    2.0   56.323990         NaN            1.0     18   
9949   3355          53    1.0   39.211416   36.159431            1.0     19   
9951   9237          25    1.0   33.516313   31.086243            1.0     13   
9954    5

Таких квартир 1556 штук. В данных по этажу и этажности дома много ошибок. Скорее всего лучше будет сделать отдельный признак говорящий о том последний этаж у квартиры или первый, для тех квартир где это можно расчитать.

#### LifeSquare и Square

In [21]:
# посмотрим на квартиры с очень большой площадью, оставим только понятные столбцы
data_train.loc[data_train['Square'] > 200, ['Id', 'Rooms', 'Square', 'LifeSquare', 'KitchenSquare',
                                            'Floor', 'HouseFloor', 'Price']]

Id  Rooms      Square  LifeSquare  KitchenSquare  Floor  HouseFloor  \
1981   7917    0.0  212.932361  211.231125            0.0      2         3.0   
1982   5548    5.0  275.645284  233.949309           26.0     12        37.0   
4262     28    2.0  604.705972         NaN            1.0     17        18.0   
4690   2307    1.0  409.425181  410.639749           10.0      4         4.0   
6977  11602    2.0  641.065193  638.163193           10.0     20        19.0   
9910  16568    4.0  200.334539  201.627361           25.0      1         2.0   

              Price  
1981  302211.260887  
1982  455264.882666  
4262  187717.242538  
4690   90470.430830  
6977  133529.681562  
9910  528560.506016

Похоже, что у квартиры с Id 28, 2307, 11602 судя по их стоимости ошибка в полях LifeSquare и Square. Значения завышены в 10 раз. Для остальных квартир площадь выглядит нормально.

In [22]:
# Похоже, что у квартиры с Id 28, 2307, 11602 судя по их стоимости ошибка в полях LifeSquare и Square. 
# Значения завышены в 10 раз. Для остальных квартир площадь выглядит нормально.
# уменьшим площади в 10 раз для данных квартир
data_train.loc[data_train['Id'].isin([28, 2307, 11602]), ['Square', 'LifeSquare']] = \
                                        data_train.loc[data_train['Id'].isin([28, 2307, 11602]), ['Square', 'LifeSquare']] / 10

In [23]:
# проверим квартиры у которых LifeSquare > Square
data_train.loc[data_train['LifeSquare'] > data_train['Square']]

Id  DistrictId  Rooms      Square  LifeSquare  KitchenSquare  Floor  \
28     8054          23    1.0   42.530043   43.967759            1.0      3   
44    10521          38    3.0  104.211396  106.340403            0.0     20   
52     2301           1    2.0   61.400054   65.224603            0.0     17   
123    8753          25    3.0   85.952306   89.803753            1.0      4   
153    9870          62    1.0   51.831473   53.491301            1.0      5   
178    2416          57    1.0   29.298168   29.770784            5.0      7   
184    3398          74    1.0   48.743665   51.011232            1.0     12   
212    1748          88    2.0    5.497061   67.628717            1.0     24   
217    5540          27    3.0   57.643613   59.425078            9.0     16   
234   12633          27    3.0   81.867166   81.884548            0.0     12   
236    3916           1    1.0   43.084413   47.071617            1.0      9   
237    3851          52    2.0   65.388475   66.591815            1.0     13   
271    7674          30    2.0   51.283020   51.575295            1.0      5   
315   14899          27    1.0   37.370830   39.184607            1.0     25   
342    7815           6    1.0   74.609609   78.533293            1.0     16   
343     716         113    3.0  125.287183  127.477137           19.0     26   
358    6006          62    3.0  121.844004  122.497641            1.0      3   
369      61           1    1.0   54.307727   55.926217            1.0      4   
378   15443           1    1.0   37.885188   40.313322           10.0     12   
379    8104          52    1.0   37.496336   38.964704           10.0      7   
392   15246           1    2.0   64.067854   65.081193            1.0     12   
401    2123          58    3.0   93.905616   94.958481            1.0      3   
478   10391          62    1.0   37.498161   40.371530            1.0     21   
495   10071          27    2.0   34.665783   36.079447            9.0      3   
498   12796           6    1.0   59.816412   60.823136            1.0     24   
506    9552          23    1.0  105.432181  106.178175            0.0      3   
544    2467          23    3.0   63.837671   64.300575            1.0      4   
554    5738          52    2.0   66.795666   67.051654            1.0      3   
561   11692         113    2.0   70.566571   70.694221           12.0     28   
574   14211          48    1.0   39.357596   40.015989            1.0     21   
...     ...         ...    ...         ...         ...            ...    ...   
9476  13789          23    1.0   29.289544   30.492156            0.0      3   
9484  10374          54    2.0   78.061116   82.171479            1.0     10   
9492   5367           1    3.0   81.227389   81.655818            0.0     14   
9582   3414           6    2.0   60.913076   63.262528            1.0      3   
9584   8403           9    2.0   56.690554   56.917296            1.0      8   
9589  16638          38    1.0  106.260300  109.246660            1.0      4   
9594   7113          62    1.0   43.906426   44.082779            1.0     13   
9595   7249           6    3.0   73.171947   74.858927            1.0      7   
9597    833          27    1.0   44.260288   45.602761           10.0      3   
9613   7657          38    1.0    4.502784    4.618547            1.0     28   
9626   3742           1    1.0   53.258610   56.655126            0.0      6   
9630  10021          27    1.0   41.755282   41.857484            1.0     13   
9646   6996          23    2.0   53.054415   54.677693            1.0      3   
9681     47           2    2.0   45.053898   47.329346            5.0      2   
9707  12302          30    1.0   46.072913   48.307844            0.0      4   
9721    396          54    3.0  110.119100  110.333763            1.0      8   
9742   9941          46    3.0   64.642890   66.400030            6.0      6   
9772   6968           6    3.0   74.505045   75.735479            1.0     15   
9793   57

Таких квартир 482 штуки. Разница между значениями небольшая. Можно будет взять максимальное значение для нового признака площади квартиры. Либо вообще не использовать LifeSquare, т.к. в нем много пропущенных значений.

In [24]:
# посмотрим на маленькие знаечния Square
data_train.loc[data_train['Square'] < 15, ['Id', 'Rooms', 'Square', 'LifeSquare', 'KitchenSquare',
                                            'Floor', 'HouseFloor', 'Price']]

Id  Rooms     Square  LifeSquare  KitchenSquare  Floor  HouseFloor  \
212    1748    2.0   5.497061   67.628717            1.0     24        22.0   
1316  11526    1.0   4.633498    1.969969            1.0     18         1.0   
1608  10202    1.0   2.596351    4.604943            1.0      3        25.0   
3280  10527    1.0   4.380726   40.805837            1.0     10        17.0   
3413   9487    1.0   5.129222    5.549458            1.0      1         1.0   
4739  12676    3.0  13.784865   15.988889            7.0      4         5.0   
4853   3224    0.0   2.377248    0.873147            0.0      1         0.0   
4900   4504    3.0   4.390331    5.610772            1.0      8        19.0   
6392  14786    1.0   1.136859    4.525736            1.0      3         1.0   
8030  13265    3.0   4.823679   79.767964            0.0      6        17.0   
8283  15744    1.0   1.988943    2.642219            1.0     21         4.0   
9294   6782    1.0   2.954309    5.257278            1.0      3         1.0   
9613   7657    1.0   4.502784    4.618547            1.0     28         1.0   

              Price  
212   412511.088764  
1316  107604.269441  
1608  137597.601458  
3280   97560.720383  
3413  369472.403061  
4739   78388.806186  
4853  126596.941798  
4900  161379.067034  
6392  181434.825589  
8030  237716.681261  
8283  458378.777006  
9294  438005.182323  
9613  483283.488083

Площади таких квартиры нужно будет заменять на статистические данные.

#### Rooms

In [25]:
# посмотрим на квартиры с 0 комнат
data_train.loc[data_train['Rooms'] == 0]

Id  DistrictId  Rooms      Square  LifeSquare  KitchenSquare  Floor  \
1397  12638          27    0.0  138.427694  136.215499            0.0      4   
1981   7917          27    0.0  212.932361  211.231125            0.0      2   
2269   7317          27    0.0   41.790881         NaN            0.0     13   
3911    770          28    0.0   49.483501         NaN            0.0     16   
4366    456           6    0.0   81.491446         NaN            0.0      4   
4853   3224          27    0.0    2.377248    0.873147            0.0      1   
6149   3159          88    0.0   38.697117   19.345131            9.0      9   
8834   9443          27    0.0   87.762616   85.125471            0.0      5   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
1397         3.0       2016   0.075424         B         B        11   
1981         3.0       2008   0.211401         B         B         9   
2269         0.0       1977   0.211401         B         B         9   
3911         0.0       2015   0.118537         B         B        30   
4366         0.0       1977   0.243205         B         B         5   
4853         0.0       1977   0.017647         B         B         2   
6149        16.0       1982   0.127376         B         B        43   
8834        15.0       1977   0.211401         B         B         9   

      Social_2  Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  \
1397      3097         0           NaN            0        0       B   
1981      1892         0           NaN            0        1       B   
2269      1892         0           NaN            0        1       B   
3911      6207         1        1183.0            1        0       B   
4366      1564         0         540.0            0        0       B   
4853       469         0           NaN            0        0       B   
6149      8429         3           NaN            3        9       B   
8834      1892         0           NaN            0        1       B   

              Price  
1397  268394.744389  
1981  302211.260887  
2269   98129.976788  
3911  217009.338463  
4366  212864.799112  
4853  126596.941798  
6149  158998.110646  
8834  219281.918007

Либо это квартиры студии, либо здесь ошибка при заполнении. Такие квартиры стоит заполнить либо 1, либо по статистическим данным.

In [26]:
# посмотрим на квартиры с большим количеством комнат
data_train.loc[data_train['Rooms'] > 5]

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
377    5927          57   10.0  59.056975   36.223072           10.0     22   
1454   8491           1   19.0  42.006046   21.779288            7.0     17   
2170  14003          99    6.0  59.414334   38.702244            6.0      7   
8849  14865           9   10.0  60.871266   38.420681           10.0      3   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
377         22.0       2002   0.090799         B         B        74   
1454        17.0       2014   0.007122         B         B         1   
2170         9.0       1969   0.033494         B         B        66   
8849         2.0       1994   0.161532         B         B        25   

      Social_2  Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  \
377      19083         2           NaN            5       15       B   
1454       264         0           NaN            0        1       B   
2170     10573         1        1322.0            3        8       B   
8849      5648         1          30.0            2        4       B   

              Price  
377   317265.323792  
1454   78364.616704  
2170  229661.964416  
8849  172329.270863

In [27]:
# посмотрим медианные значения площади для 1, 2 и 3 комнатных квартир
data_train.loc[data_train['Rooms'].isin([1,2,3]), ['Rooms', 'Square']].groupby(by='Rooms').median()

Square
Rooms           
1.0    40.406590
2.0    55.841812
3.0    77.413643

In [28]:
# заменим значения для квартир с аномально большим количеством комнат на медианные
data_train.loc[data_train['Id'].isin([5927, 14003, 14865]), 'Rooms'] = 2

data_train.loc[data_train['Id'] == 8491, 'Rooms'] = 1

### Test train split

In [153]:
from sklearn.model_selection import train_test_split

# перед дальнейшей обработкой данных необходимо разбить датасет на train и valid
train, valid = train_test_split(data_train, test_size=0.3, random_state=RANDOM_STATE)

# проверяем размеры получившихся DataFrame
train.shape, valid.shape

((7000, 20), (3000, 20))

### Data prepare (подготовка данных)

В данном разделе расчитаем необходимые статистики. Дополним ими данные. Напишем функции для очистки данных основываясь на выводах из предидущего раздела. Обработаем категориальные признаки.

#### Категориальные признаки

In [127]:
# начнем с обработки категориальных признаков
# посмотрим как они выглядят
train.describe(include=['object'])

Ecology_2 Ecology_3 Shops_2
count       7000      7000    7000
unique         2         2       2
top            B         B       B
freq        6936      6798    6416

In [128]:
# посмотрим какие встречаются значения
for cat_f in train.select_dtypes(include=['object']).columns:
    print(train[cat_f].unique())

['B' 'A']
['B' 'A']
['B' 'A']


In [129]:
def prepare_category(df, cat_feats=['Ecology_2', 'Ecology_3', 'Shops_2']):
    ''' Приводит категориальные признаки к числовым
    '''
    df_copy = df.copy()
    for f in cat_feats:
        df_copy.loc[:, f] = df[f].map({'A': 1, 'B': 0})
    return df_copy

In [154]:
train = prepare_category(train)
valid = prepare_category(valid)

#### Расчет статистик

In [155]:
# посчитаем различные статистики по train

# количество квартир в районе:
stats_distr_1 = train['DistrictId'].value_counts(normalize=True).reset_index().\
                                                                 rename(columns={'index':'DistrictId', 
                                                                                 'DistrictId':'flat_qty_distr'})

# средняя цена за квартиру по районам и кол-ву комнат
stats_distr_rooms_1 = train.groupby(['DistrictId', 'Rooms'], as_index=False)[['Price']].mean().\
                                                                            rename(columns={'Price':'mean_price_distr_rooms'})

# средняя цена за квартиру по кол-ву комнат
stats_rooms_1 = train.groupby(['Rooms'], as_index=False)[['Price']].mean().rename(columns={'Price':'mean_price_rooms'})

# медианная площадь по району и кол-ву комнат
stats_distr_rooms_2 = train.groupby(['DistrictId', 'Rooms'], as_index=False)[['Square']].median().\
                                                                            rename(columns={'Square':'mean_square_distr_rooms'})

# медианная площадь по кол-ву комнат
stats_rooms_2 = train.groupby(['Rooms'], as_index=False)[['Square']].median().\
                                                                            rename(columns={'Square':'mean_square_rooms'})

In [132]:
def add_stat_distr_1(df, stats=stats_distr_1):
    df_copy = df.copy()
    df_copy = pd.merge(df_copy, stats, on='DistrictId', how='left')
    df_copy['flat_qty_distr'] = df_copy['flat_qty_distr'].fillna(stats['flat_qty_distr'].min())
    return df_copy

In [133]:
def add_stat_distr_rooms(df, stats_1=stats_distr_rooms_1, stats_2=stats_rooms_1):
    df_copy = df.copy()
    df_copy = pd.merge(df_copy, stats_1, on=['DistrictId', 'Rooms'], how='left')
    df_copy = pd.merge(df_copy, stats_2, on='Rooms', how='left')
    
    df_copy['mean_price_rooms'] = df_copy['mean_price_rooms'].fillna(stats_2['mean_price_rooms'].mean())
    df_copy['mean_price_distr_rooms'] = df_copy['mean_price_distr_rooms'].fillna(df_copy['mean_price_rooms'])
    return df_copy

In [134]:
def add_stat_distr_rooms_2(df, stats_1=stats_distr_rooms_2, stats_2=stats_rooms_2):
    df_copy = df.copy()
    df_copy = pd.merge(df_copy, stats_1, on=['DistrictId', 'Rooms'], how='left')
    df_copy = pd.merge(df_copy, stats_2, on='Rooms', how='left')
    
    df_copy['mean_square_rooms'] = df_copy['mean_square_rooms'].fillna(stats_2['mean_square_rooms'].mean())
    df_copy['mean_square_distr_rooms'] = df_copy['mean_square_distr_rooms'].fillna(df_copy['mean_square_rooms'])
    return df_copy

In [156]:
train = add_stat_distr_1(train)
valid = add_stat_distr_1(valid)

train = add_stat_distr_rooms(train)
valid = add_stat_distr_rooms(valid)

train = add_stat_distr_rooms_2(train)
valid = add_stat_distr_rooms_2(valid)

#### Коррекция HouseFloor и Floor

In [136]:
import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format = 'svg'

In [137]:
# посмотрим сколькоэтажные дома встречаются чаще всего
train['HouseFloor'].value_counts().head(5)

17.0    1634
9.0      977
12.0     749
5.0      707
14.0     446
Name: HouseFloor, dtype: int64

In [138]:
import numpy as np

In [139]:
def coorect_HouseFloor(floor, sorted_HouseFloor):
    for housefloor in sorted_HouseFloor:
        if floor.item() <= housefloor:
            return housefloor
    return floor.item()  # если квартира на этаже который выше часто встречаемых HouseFloor


def prepare_HouseFloor(df, source_df):
    df_copy = df.copy()
    sorted_HouseFloor = list(source_df['HouseFloor'].value_counts().index)[:4]
    sorted_HouseFloor.sort()
    df_copy.loc[df_copy['HouseFloor'] == 0, 'HouseFloor'] = \
        df.loc[df['HouseFloor'] == 0, ['Floor']].apply(coorect_HouseFloor, axis=1, args=[sorted_HouseFloor])
    return df_copy


# решим проблему Floor > HouseFloor 
# для тех домов, где HouseFloor = 1 будем Floor менять местами с HouseFloor
def prepare_Floor_HouseFloor_ex(df):
    df_copy = df.copy()
    df_copy.loc[(df_copy['Floor'] > df_copy['HouseFloor']) & (df_copy['HouseFloor'] == 1), ['Floor', 'HouseFloor']] = \
        df.loc[(df['Floor'] > df['HouseFloor']) & (df['HouseFloor'] == 1), ['HouseFloor', 'Floor']].\
            rename(columns={'HouseFloor':'Floor', 'Floor':'HouseFloor'})
    return df_copy


# для тех домов, где HouseFloor > 1 будем Floor приравнивать к HouseFloor
def prepare_Floor_HouseFloor(df):
    df_copy = df.copy()
    df_copy.loc[(train['Floor'] > train['HouseFloor']) & (train['HouseFloor'] > 1), 'Floor'] = \
        df.loc[(train['Floor'] > train['HouseFloor']) & (train['HouseFloor'] > 1), 'HouseFloor']
    return df_copy



# создадим два признака первый этаж и последний этаж
def create_feat_last_floor(df):
    df_copy = df.copy()
    df_copy['LastFloor'] = (df['Floor'] == df['HouseFloor'])
    return df_copy


# создадим два признака первый этаж и последний этаж
def create_feat_first_floor(df):
    df_copy = df.copy()
    df_copy['FirstFloor'] = (df['Floor'] == 1)
    return df_copy

In [157]:
train = prepare_HouseFloor(train, source_df=train)
train = prepare_Floor_HouseFloor(train)
train = prepare_Floor_HouseFloor_ex(train)
train = create_feat_last_floor(train)
train = create_feat_first_floor(train)

valid = prepare_HouseFloor(valid, source_df=train)
valid = prepare_Floor_HouseFloor(valid)
valid = prepare_Floor_HouseFloor_ex(valid)
valid = create_feat_last_floor(valid)
valid = create_feat_first_floor(valid)


#### Коррекция KitchenSquare

In [141]:
# Если площадь кухни составляет > 80% от общей площади, то зануляем ее
def prepare_KitchenSquare(df):
    df_copy = df.copy()
    df_copy.loc[df_copy['KitchenSquare'] / df_copy['Square'] > 0.8, 'KitchenSquare'] = 0
    return df_copy

In [158]:
train = prepare_KitchenSquare(train)

valid = prepare_KitchenSquare(valid)

#### Коррекция LifeSquare и Square

In [147]:
# уберем все аномально большие занчения LifeSquare
def prepare_LifeSquare_max(df):
    df_copy = df.copy()
    df_copy.loc[(df_copy['LifeSquare'] / df_copy['Square']) > 1.2, 'LifeSquare'] = np.NaN
    return df_copy

In [123]:
# Поменяем местами LifeSquare и Square для тех квартир где LifeSquare > Square
def prepare_Square_LifeSquare_ex(df):
    df_copy = df.copy()
    df_copy.loc[(df_copy['LifeSquare'] > df_copy['Square']), ['LifeSquare', 'Square']] = \
        df.loc[(df['LifeSquare'] > df['Square']), ['Square', 'LifeSquare']].\
            rename(columns={'LifeSquare':'Square', 'Square':'LifeSquare'})
    return df_copy

In [161]:
train = prepare_LifeSquare_max(train)
valid = prepare_LifeSquare_max(valid)

train = prepare_Square_LifeSquare_ex(train)
valid = prepare_Square_LifeSquare_ex(valid)

In [163]:
# посмотрим на отношение LifeSquare к Square
(train['LifeSquare'] / train['Square']).median()

0.6170119590685053

In [164]:
# считаем статистику по соотношению LifeSquare к Square
stats_LifeSquare_Square_perc = train.loc[train['LifeSquare'] > 0, ['Rooms', 'Square', 'LifeSquare']]\
    .groupby(by=['Rooms'], as_index=False).median()

stats_LifeSquare_Square_perc['LS_S_perc'] = \
    stats_LifeSquare_Square_perc['LifeSquare'] / stats_LifeSquare_Square_perc['Square']

stats_LifeSquare_Square_perc = stats_LifeSquare_Square_perc.drop(['Square', 'LifeSquare'], axis=1)

In [89]:
# добавляем статистику в датасет
def add_stat_LifeSquare_Square_perc(df, stats=stats_LifeSquare_Square_perc):
    df_copy = df.copy()
    df_copy = pd.merge(df_copy, stats, on='Rooms', how='left')
    df_copy['LS_S_perc'] = df_copy['LS_S_perc'].fillna(stats['LS_S_perc'].median())
    return df_copy

# заполняем поле LifeSquare
def fillna_LifeSquare(df):
    df_copy = df.copy()
    df_copy.loc[df_copy['LifeSquare'].isna(), 'LifeSquare'] = df_copy.loc[df_copy['LifeSquare'].isna(), 'Square'] * \
                                                                df_copy.loc[df_copy['LifeSquare'].isna(), 'LS_S_perc']
    return df_copy

# так же для всех квартиры у которых соотношение LifeSquare к Square < 30% заменим LifeSquare
def prepare_LifeSquare_small(df):
    df_copy = df.copy()
    df_copy.loc[(df_copy['LifeSquare'] / df_copy['Square']) < 30, 'LifeSquare'] = \
        df_copy.loc[(df_copy['LifeSquare'] / df_copy['Square']) < 30, 'Square'] * \
            df_copy.loc[(df_copy['LifeSquare'] / df_copy['Square']) < 30, 'LS_S_perc']
    return df_copy

In [165]:
train = add_stat_LifeSquare_Square_perc(train)
train = fillna_LifeSquare(train)
train = prepare_LifeSquare_small(train)

valid = add_stat_LifeSquare_Square_perc(valid)
valid = fillna_LifeSquare(valid)
valid = prepare_LifeSquare_small(valid)

In [93]:
def prepare_Square(df):
    df_copy = df.copy()
    df_copy.loc[df_copy['Square'] < 15, 'Square'] = df.loc[df['Square'] < 15, 'mean_square_distr_rooms']
    return df_copy

In [167]:
train = prepare_Square(train)

valid = prepare_Square(valid)

In [172]:
# заменим nan в поле Healthcare_1 на 0
def fillna_Healthcare_1(df):
    df_copy = df.copy()
    df_copy['Healthcare_1'] = df_copy['Healthcare_1'].fillna(0)
    return df_copy

In [175]:
train = fillna_Healthcare_1(train)
valid = fillna_Healthcare_1(valid)

### Model

In [179]:
from sklearn.ensemble import RandomForestRegressor as RF
from sklearn.metrics import r2_score as r2, mean_squared_error as mse

In [188]:
def fit_and_score(model, X_train, X_valid, y_train, y_valid):
    model.fit(X_train, y_train.values.ravel())
    y_train_pred = model.predict(X_train)
    y_valid_pred = model.predict(X_valid)
    r2_train = r2(y_train, y_train_pred)
    r2_valid = r2(y_valid, y_valid_pred)
    return r2_train, r2_valid

In [228]:
rf = RF(random_state=RANDOM_STATE,
        n_estimators=1000,
        max_depth=14,
        max_features=16,
        n_jobs=-1)

In [231]:
feats = [
#     'DistrictId',
    'Rooms',
    'Square',
    'LifeSquare',
    'KitchenSquare',
    'Floor',
    'HouseFloor',
    'HouseYear',
    'Ecology_1',
    'Ecology_2',
    'Ecology_3',
    'Social_1',
    'Social_2', 
    'Social_3', 
    'Healthcare_1',
    'Helthcare_2', 
    'Shops_1', 
    'Shops_2', 
    'flat_qty_distr',
    'mean_price_distr_rooms', 
    'mean_price_rooms', 
    'mean_square_distr_rooms',
    'mean_square_rooms',
    'LastFloor', 
    'FirstFloor', 
#     'LS_S_perc'
]

target = ['Price']

In [232]:
fit_and_score(rf, train[feats], valid[feats], train[target], valid[target])

(0.9513131543759897, 0.7029320252194721)